version: '2'

services:

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile-70-xdebug
        volumes_from:
            - application
        volumes:
            - ./logs/php-fpm/:/tmp/xdebug_log
        links:
            - workspace
        expose:
            - "9000"
        environment:
            XDEBUG_CONFIG: "remote_host=172.17.0.1"
            PHP_IDE_CONFIG: "serverName=laradock"

### Laravel Application Code Container ######################

    application:
        build: ./application
        volumes:
            - ../:/var/www/getaimee.com

### Databases Data Container ################################

    data:
        build: ./data
        volumes:
            - /var/lib/mysql:/var/lib/mysql
            - /var/lib/postgres:/var/lib/postgres
            - /var/lib/mariadb:/var/lib/mariadb
            - /var/lib/memcached:/var/lib/memcached
            - /var/lib/redis:/data
            - /var/lib/neo4j:/var/lib/neo4j/data
            - /var/lib/mongo:/data/db

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes_from:
            - application
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

### MySQL Container #########################################

    mysql:
        build: ./mysql
        volumes_from:
            - data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: aimee
            MYSQL_USER: aimee
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### PostgreSQL Container ####################################

    postgres:
        build: ./postgres
        volumes_from:
            - data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: aimee
            POSTGRES_USER: aimee
            POSTGRES_PASSWORD: secret

### MariaDB Container #######################################

    mariadb:
        build: ./mariadb
        volumes_from:
            - data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: aimee
            MYSQL_USER: aimee
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### Neo4j Container #########################################

    neo4j:
        build: ./neo4j
        ports:
            - "7474:7474"
            - "1337:1337"
        environment:
            - NEO4J_AUTH=aimee:secret
        volumes_from:
            - data

### MongoDB Container #######################################

    mongo:
        build: ./mongo
        ports:
            - "27017:27017"
        volumes_from:
            - data

### Redis Container #########################################

    redis:
        build: ./redis
        volumes_from:
            - data
        ports:
            - "6379:6379"

### Memcached Container #####################################

    memcached:
        build: ./memcached
        volumes_from:
            - data
        ports:
            - "11211:11211"
        links:
            - php-fpm

### Beanstalkd Container ####################################

    beanstalkd:
        build: ./beanstalkd
        ports:
            - "11300:11300"
        privileged: true
        links:
            - php-fpm

### Beanstalkd Console Container ############################

    beanstalkd-console:
        build: ./beanstalkd-console
        ports:
            - "2080:2080"
        links:
            - beanstalkd

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                INSTALL_PRESTISSIMO: ${INSTALL_PRESTISSIMO}
        volumes_from:
            - application
        tty: true

### Add more Containers below ###############################

    lb:
        image: dockercloud/haproxy
        links:
            - php-fpm
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        volumes_from:
            - application
        ports:
            - 80:80
        environment:
            EXTRA_GLOBAL_SETTINGS: "debug"
            DEFAULT_SSL_CERT:
