FROM nginx:latest

MAINTAINER aimee

ADD nginx.conf /etc/nginx/
ADD letsencrypt.conf /etc/nginx/
ADD ssl.conf /etc/nginx/
ADD aimee.nossl.conf /etc/nginx/sites-available/

RUN echo "upstream php-upstream { server php-fpm:9000; }" > /etc/nginx/conf.d/upstream.conf

RUN usermod -u 1000 www-data

EXPOSE 80 443
